/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_company_poc_project_MbusApplication */

#ifndef _Included_ch_company_poc_project_MbusApplication
#define _Included_ch_company_poc_project_MbusApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_company_poc_project_MbusApplication
 * Method:    decodeHexValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_company_poc_project_MbusApplication_decodeHexValue
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
